### ISSUE TITLE
it'd be cool if it showed ping from the us, and from the uk, since there is a mix of players 

### ISSUE THREAD

**Issue by Zubbbz** [Derpius/pythonsourceserverdiscordbot#30]
https://github.com/Derpius/pythonsourceserverdiscordbot/blob/d415aee517e9e6d30e930d973fda1ef184182840/bot/cogs/usercommands.py#L31-L40

**Comment by Derpius** [comment]
How is it going to show the ping **from/to** someone else's machine

**Comment by Zubbbz** [comment]
it wont, you'd find a site(s) that let you get their ping to the gmod server for a rough estimate.

**Comment by Derpius** [comment]
You're forgetting that my bot is designed to support multiple game servers, including game servers running on an entirely different network, and that `status` is just to check the state of a server, not the viability of playing on it from any particular region
