### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by Zubbbz** [Derpius/pythonsourceserverdiscordbot#32]
**Feature description**
Clearer indication in the join and leave messages so that it is more clear when someone leaves and joins, especially to non technical users who might not understand what some of the messages mean.

**Possible implementation**
Add an emoji before the join / leave messages
example: 
![image](https://user-images.githubusercontent.com/37497090/175255902-fd7f6ac3-325d-4ff3-97f8-e40853f29f18.png)

**Comment by Derpius** [comment]
The join/leave messages aren't on github, they're local to our server and any other install of the bot
